var miVariableUno = 250;
var miVariableDos = 50;
var miVariableTres = 5;
const espacioEnBlanco = " ";
let resultadoA = miVariableUno + miVariableDos + espacioEnBlanco;
let resultadoB = miVariableUno - miVariableDos + espacioEnBlanco;
let resultadoC = miVariableUno / miVariableDos + espacioEnBlanco;
let resultadoD = miVariableUno * miVariableDos + espacioEnBlanco;
let resultadoE = miVariableUno * miVariableTres + miVariableDos;

var incremento = ++miVariableUno;
var decremento = --miVariableUno;

var resto = miVariableDos % miVariableUno;


console.log("La suma es: ", resultadoA);

console.log("La resta es: ", resultadoB);

console.log("La division es: ", resultadoC);

console.log("La multiplicación es: ", resultadoD);

console.log("La multiplicación y suma es: ", resultadoE);

console.log("El incremento es: ", incremento);

console.log("El decremento es: ", decremento);

console.log("El resto es: ", resto);















